apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MQ==
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: d29yZHByZXNz
  MYSQL_PASSWORD: MQ==
