apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-claim
  namespace: wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

